application:
  port: 8000

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "56e7d520-8f45-46cb-88b6-8706a69791cb"